apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - podinfo.yaml
  - pravega.yaml
  - jetstack.yaml
  - kafka-operator.yaml
  - codecentric.yaml
  - zenko.yaml
