---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - namespace.yaml
  - release.yaml
  - storageclass.yaml
  - volume.yaml
configMapGenerator:
  - name: keycloak-values
    files:
      - values.yaml=values.yaml